name:                proto-bogl-explorer
version:             0.1.0.0
github:              "montymxb/proto-bogl-explorer"
license:             BSD3
author:              "Benjamin Friedman Wilson"
maintainer:          "friedman.benjamin@gmail.com"
copyright:           "2021 Benjamin Friedman Wilson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/montymxb/proto-bogl-explorer#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- wai
- warp
- aeson
- unordered-containers
- text
- wai-extra
- wai-cors
- process
- directory
- vector
- ProgramConceptClassifier
library:
  source-dirs: src

executables:
  proto-bogl-explorer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-bogl-explorer

tests:
  proto-bogl-explorer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-bogl-explorer
